// List
export const LIST_HAS_ERRORED = 'LIST_HAS_ERRORED';
export const LIST_IS_LOADING = 'LIST_IS_LOADING';
export const LIST_FETCH_DATA_SUCCESS = 'LIST_FETCH_DATA_SUCCESS';

// Details
export const DETAILS_HAS_ERRORED = 'DETAILS_HAS_ERRORED';
export const DETAILS_IS_LOADING = 'DETAILS_IS_LOADING';
export const DETAILS_FETCH_DATA_SUCCESS = 'DETAILS_FETCH_DATA_SUCCESS';

// Settings
export const SETTINGS_SET_CURRENCY = 'SETTINGS_SET_CURRENCY';
